import { execFile } from "node:child_process";
import { homedir } from "node:os";
import { chmod, mkdir, rename, writeFile } from "node:fs/promises";
import path from "node:path";

export interface LarkCliStatus {
  available: boolean;
  version?: string;
  error?: string;
}

export type LarkCliExecFile = (
  file: string,
  args: readonly string[],
  options: { timeout: number; maxBuffer: number },
) => Promise<{ stdout: string | Buffer; stderr: string | Buffer }>;

const LARK_CLI_STATUS_TIMEOUT_MS = 3_000;

export interface LarkCliBridgeBindingConfigInput {
  appId: string;
  stateDir: string;
  brand: "feishu" | "lark";
  homeDir?: string;
  nodePath?: string;
  entrypoint?: string;
}

export interface LarkCliBridgeBindingConfig {
  appDir: string;
  configPath: string;
  secretsGetterPath: string;
}

export async function detectLarkCliStatus(execFileImpl: LarkCliExecFile = defaultExecFile): Promise<LarkCliStatus> {
  try {
    const { stdout, stderr } = await execFileImpl("lark-cli", ["--version"], {
      timeout: LARK_CLI_STATUS_TIMEOUT_MS,
      maxBuffer: 64 * 1024,
    });
    const output = `${bufferToString(stdout)}\n${bufferToString(stderr)}`.trim();
    const version = output.split(/\r?\n/).map((line) => line.trim()).find(Boolean);
    return {
      available: true,
      ...(version ? { version } : {}),
    };
  } catch (error) {
    return {
      available: false,
      error: renderLarkCliError(error),
    };
  }
}

export async function ensureLarkCliBridgeBindingConfig(input: LarkCliBridgeBindingConfigInput): Promise<LarkCliBridgeBindingConfig> {
  const appDir = path.join(input.homeDir ?? homedir(), ".lark-channel");
  const configPath = path.join(appDir, "config.json");
  const secretsGetterPath = path.join(appDir, "secrets-getter");
  const stateDir = path.resolve(input.stateDir);
  const nodePath = input.nodePath ?? process.execPath;
  const entrypoint = path.resolve(input.entrypoint ?? process.argv[1] ?? "dist/src/index.js");

  await mkdir(appDir, { recursive: true });
  const wrapper = [
    "#!/bin/sh",
    "# Auto-generated by cc-telegram-bridge. Do not edit.",
    "# Feeds lark-cli exec-provider secret requests through the bridge Lark state dir.",
    `CCTB_LARK_STATE_DIR=${shellQuote(stateDir)} exec ${shellQuote(nodePath)} ${shellQuote(entrypoint)} lark secrets get "$@"`,
    "",
  ].join("\n");
  await writeAtomic(secretsGetterPath, wrapper, 0o700);

  const config = {
    accounts: {
      app: {
        id: input.appId,
        secret: {
          source: "exec",
          provider: "bridge",
          id: `app-${input.appId}`,
        },
        tenant: input.brand,
      },
    },
    secrets: {
      providers: {
        bridge: {
          source: "exec",
          command: secretsGetterPath,
          args: [],
        },
      },
    },
  };
  await writeAtomic(configPath, `${JSON.stringify(config, null, 2)}\n`, 0o600);

  return {
    appDir,
    configPath,
    secretsGetterPath,
  };
}

function defaultExecFile(
  file: string,
  args: readonly string[],
  options: { timeout: number; maxBuffer: number },
): Promise<{ stdout: string; stderr: string }> {
  return new Promise((resolve, reject) => {
    execFile(file, [...args], options, (error, stdout, stderr) => {
      if (error) {
        reject(error);
        return;
      }
      resolve({
        stdout: bufferToString(stdout),
        stderr: bufferToString(stderr),
      });
    });
  });
}

function bufferToString(value: string | Buffer): string {
  return Buffer.isBuffer(value) ? value.toString("utf8") : value;
}

function renderLarkCliError(error: unknown): string {
  if (error instanceof Error) {
    return error.message;
  }
  return String(error);
}

async function writeAtomic(filePath: string, content: string, mode: number): Promise<void> {
  const tempPath = `${filePath}.tmp-${process.pid}-${Date.now()}`;
  await writeFile(tempPath, content, "utf8");
  await chmod(tempPath, mode);
  await rename(tempPath, filePath);
}

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}
