import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

import { resolveLarkInstanceName, type LarkRuntimeEnv } from "./config.js";

export const LARK_ENV_FILE_NAME = "lark.env";

export function resolveLarkStateDir(env: Pick<LarkRuntimeEnv, "HOME" | "USERPROFILE" | "CCTB_LARK_STATE_DIR" | "CODEX_TELEGRAM_STATE_DIR">): string {
  if (env.CCTB_LARK_STATE_DIR) {
    return env.CCTB_LARK_STATE_DIR;
  }
  if (env.CODEX_TELEGRAM_STATE_DIR) {
    return env.CODEX_TELEGRAM_STATE_DIR;
  }
  const homeDir = env.HOME ?? env.USERPROFILE;
  if (!homeDir) {
    throw new Error(process.platform === "win32" ? "USERPROFILE or HOME is required" : "HOME or USERPROFILE is required");
  }
  return path.join(homeDir, ".cctb", "lark");
}

export function resolveLarkEnvFilePath(env: Pick<LarkRuntimeEnv, "HOME" | "USERPROFILE" | "CCTB_LARK_STATE_DIR" | "CODEX_TELEGRAM_STATE_DIR">): string {
  return path.join(resolveLarkStateDir(env), LARK_ENV_FILE_NAME);
}

export async function loadLarkRuntimeEnv(env: LarkRuntimeEnv): Promise<LarkRuntimeEnv> {
  let envPath: string;
  try {
    envPath = resolveLarkEnvFilePath(env);
  } catch {
    return env;
  }

  let parsed: Partial<LarkRuntimeEnv>;
  try {
    parsed = parseLarkEnvFile(await readFile(envPath, "utf8"));
  } catch (error) {
    if (typeof error === "object" && error !== null && "code" in error && (error as NodeJS.ErrnoException).code === "ENOENT") {
      return env;
    }
    throw error;
  }

  return {
    ...env,
    LARK_APP_ID: env.LARK_APP_ID ?? parsed.LARK_APP_ID,
    LARK_APP_SECRET: env.LARK_APP_SECRET ?? parsed.LARK_APP_SECRET,
    LARK_DOMAIN: env.LARK_DOMAIN ?? parsed.LARK_DOMAIN,
    CCTB_LARK_STATE_DIR: env.CCTB_LARK_STATE_DIR ?? parsed.CCTB_LARK_STATE_DIR,
    LARK_REQUIRE_MENTION_IN_GROUP: env.LARK_REQUIRE_MENTION_IN_GROUP ?? parsed.LARK_REQUIRE_MENTION_IN_GROUP,
    CCTB_LARK_DEBUG: env.CCTB_LARK_DEBUG ?? parsed.CCTB_LARK_DEBUG,
    TAROCUB_INSTANCE: env.TAROCUB_INSTANCE ?? parsed.TAROCUB_INSTANCE ?? parsed.CODEX_TELEGRAM_INSTANCE,
    CODEX_TELEGRAM_INSTANCE: env.CODEX_TELEGRAM_INSTANCE ?? parsed.CODEX_TELEGRAM_INSTANCE,
  };
}

export async function writeLarkEnvFile(
  env: Pick<LarkRuntimeEnv, "HOME" | "USERPROFILE" | "CCTB_LARK_STATE_DIR" | "CODEX_TELEGRAM_STATE_DIR" | "TAROCUB_INSTANCE" | "CODEX_TELEGRAM_INSTANCE">,
  values: {
    appId: string;
    appSecret: string;
    domain?: string;
    requireMentionInGroup?: boolean;
  },
): Promise<string> {
  const stateDir = resolveLarkStateDir(env);
  const instanceName = resolveLarkInstanceName(env);
  await mkdir(stateDir, { recursive: true, mode: 0o700 });
  const envPath = path.join(stateDir, LARK_ENV_FILE_NAME);
  const lines = [
    "# Generated by TaroCub lark wizard. Do not commit this file.",
    `LARK_APP_ID=${quoteEnvValue(values.appId)}`,
    `LARK_APP_SECRET=${quoteEnvValue(values.appSecret)}`,
    ...(values.domain ? [`LARK_DOMAIN=${quoteEnvValue(values.domain)}`] : []),
    `CCTB_LARK_STATE_DIR=${quoteEnvValue(stateDir)}`,
    `TAROCUB_INSTANCE=${quoteEnvValue(instanceName)}`,
    `LARK_REQUIRE_MENTION_IN_GROUP=${quoteEnvValue(values.requireMentionInGroup === false ? "false" : "true")}`,
    "",
  ];
  await writeFile(envPath, lines.join("\n"), { encoding: "utf8", mode: 0o600 });
  return envPath;
}

function parseLarkEnvFile(content: string): Partial<LarkRuntimeEnv> {
  const result: Partial<LarkRuntimeEnv> = {};
  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) {
      continue;
    }
    const equalsIndex = line.indexOf("=");
    if (equalsIndex <= 0) {
      continue;
    }
    const key = line.slice(0, equalsIndex).trim();
    const value = parseEnvValue(line.slice(equalsIndex + 1).trim());
    if (isSupportedLarkEnvKey(key)) {
      result[key] = value;
    }
  }
  return result;
}

function isSupportedLarkEnvKey(key: string): key is keyof Pick<
  LarkRuntimeEnv,
  "LARK_APP_ID" | "LARK_APP_SECRET" | "LARK_DOMAIN" | "CCTB_LARK_STATE_DIR" | "LARK_REQUIRE_MENTION_IN_GROUP" | "CCTB_LARK_DEBUG" | "TAROCUB_INSTANCE" | "CODEX_TELEGRAM_INSTANCE"
> {
  return key === "LARK_APP_ID" ||
    key === "LARK_APP_SECRET" ||
    key === "LARK_DOMAIN" ||
    key === "CCTB_LARK_STATE_DIR" ||
    key === "LARK_REQUIRE_MENTION_IN_GROUP" ||
    key === "CCTB_LARK_DEBUG" ||
    key === "TAROCUB_INSTANCE" ||
    key === "CODEX_TELEGRAM_INSTANCE";
}

function parseEnvValue(value: string): string {
  if (value.length >= 2 && value.startsWith("\"") && value.endsWith("\"")) {
    return value.slice(1, -1).replace(/\\(["\\$`])/g, "$1").replace(/\\n/g, "\n");
  }
  if (value.length >= 2 && value.startsWith("'") && value.endsWith("'")) {
    return value.slice(1, -1).replace(/'\\''/g, "'");
  }
  return value;
}

function quoteEnvValue(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, "\\\"").replace(/\$/g, "\\$").replace(/`/g, "\\`").replace(/\n/g, "\\n")}"`;
}
