import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

import { resolveDefaultLarkStateDir, resolveLarkInstanceName, type LarkRuntimeEnv } from "./config.js";

export const LARK_ENV_FILE_NAME = "lark.env";

export function resolveLarkStateDir(env: Pick<LarkRuntimeEnv, "HOME" | "USERPROFILE" | "CCTB_LARK_INSTANCE" | "TAROCUB_INSTANCE" | "CCTB_LARK_STATE_DIR" | "CODEX_TELEGRAM_STATE_DIR">): string {
  if (env.CCTB_LARK_STATE_DIR) {
    return env.CCTB_LARK_STATE_DIR;
  }
  if (env.CCTB_LARK_INSTANCE || env.TAROCUB_INSTANCE) {
    return resolveDefaultLarkStateDir(env);
  }
  if (env.CODEX_TELEGRAM_STATE_DIR) {
    return env.CODEX_TELEGRAM_STATE_DIR;
  }
  return resolveDefaultLarkStateDir(env);
}

export function resolveLarkEnvFilePath(env: Pick<LarkRuntimeEnv, "HOME" | "USERPROFILE" | "CCTB_LARK_INSTANCE" | "TAROCUB_INSTANCE" | "CCTB_LARK_STATE_DIR" | "CODEX_TELEGRAM_STATE_DIR">): string {
  return path.join(resolveLarkStateDir(env), LARK_ENV_FILE_NAME);
}

export async function loadLarkRuntimeEnv(env: LarkRuntimeEnv): Promise<LarkRuntimeEnv> {
  let envPath: string;
  try {
    envPath = resolveLarkEnvFilePath(env);
  } catch {
    return env;
  }

  let parsed: Partial<LarkRuntimeEnv>;
  try {
    parsed = parseLarkEnvFile(await readFile(envPath, "utf8"));
  } catch (error) {
    if (typeof error === "object" && error !== null && "code" in error && (error as NodeJS.ErrnoException).code === "ENOENT") {
      return env;
    }
    throw error;
  }

  const larkInstance = env.CCTB_LARK_INSTANCE
    ?? env.TAROCUB_INSTANCE
    ?? parsed.CCTB_LARK_INSTANCE
    ?? parsed.TAROCUB_INSTANCE
    ?? parsed.CODEX_TELEGRAM_INSTANCE;

  return {
    ...env,
    LARK_APP_ID: env.LARK_APP_ID ?? parsed.LARK_APP_ID,
    LARK_APP_SECRET: env.LARK_APP_SECRET ?? parsed.LARK_APP_SECRET,
    LARK_DOMAIN: env.LARK_DOMAIN ?? parsed.LARK_DOMAIN,
    CCTB_LARK_STATE_DIR: env.CCTB_LARK_STATE_DIR ?? parsed.CCTB_LARK_STATE_DIR,
    CCTB_LARK_INSTANCE: larkInstance,
    LARK_REQUIRE_MENTION_IN_GROUP: env.LARK_REQUIRE_MENTION_IN_GROUP ?? parsed.LARK_REQUIRE_MENTION_IN_GROUP,
    CCTB_LARK_DEBUG: env.CCTB_LARK_DEBUG ?? parsed.CCTB_LARK_DEBUG,
    TAROCUB_INSTANCE: env.TAROCUB_INSTANCE ?? larkInstance,
    CODEX_TELEGRAM_INSTANCE: env.CODEX_TELEGRAM_INSTANCE ?? parsed.CODEX_TELEGRAM_INSTANCE,
  };
}

/**
 * Pass non-whitelisted keys from the instance's lark.env through into the process
 * environment so the spawned engine (claude/codex) — which inherits `{ ...process.env }`
 * — can see per-instance secrets such as MCP API tokens (e.g. `IFIND_TOKEN`). The
 * whitelisted Lark keys are owned by loadLarkRuntimeEnv and skipped here; an existing
 * value in the target env always wins (env beats file). Returns the names of the keys
 * applied — names only, since the values are secrets and must never be logged.
 */
export async function applyLarkEnvPassthrough(
  env: Pick<LarkRuntimeEnv, "HOME" | "USERPROFILE" | "CCTB_LARK_INSTANCE" | "TAROCUB_INSTANCE" | "CCTB_LARK_STATE_DIR" | "CODEX_TELEGRAM_STATE_DIR">,
  target: NodeJS.ProcessEnv = process.env,
): Promise<string[]> {
  let envPath: string;
  try {
    envPath = resolveLarkEnvFilePath(env);
  } catch {
    return [];
  }

  let content: string;
  try {
    content = await readFile(envPath, "utf8");
  } catch (error) {
    if (typeof error === "object" && error !== null && "code" in error && (error as NodeJS.ErrnoException).code === "ENOENT") {
      return [];
    }
    throw error;
  }

  const applied: string[] = [];
  for (const [key, value] of Object.entries(parseLarkEnvExtras(content))) {
    // Never clobber a value already present in the target env (env beats file).
    if (target[key] !== undefined) {
      continue;
    }
    target[key] = value;
    applied.push(key);
  }
  return applied;
}

export async function writeLarkEnvFile(
  env: Pick<LarkRuntimeEnv, "HOME" | "USERPROFILE" | "CCTB_LARK_INSTANCE" | "CCTB_LARK_STATE_DIR" | "CODEX_TELEGRAM_STATE_DIR" | "TAROCUB_INSTANCE" | "CODEX_TELEGRAM_INSTANCE">,
  values: {
    appId: string;
    appSecret: string;
    domain?: string;
    requireMentionInGroup?: boolean;
  },
): Promise<string> {
  const stateDir = resolveLarkStateDir(env);
  const instanceName = resolveLarkInstanceName(env);
  await mkdir(stateDir, { recursive: true, mode: 0o700 });
  const envPath = path.join(stateDir, LARK_ENV_FILE_NAME);
  // Preserve any extra (non-whitelisted) keys already in the file — e.g. MCP API
  // tokens like IFIND_TOKEN the operator added for the engine. Regenerating lark.env
  // on every service start must not silently drop them.
  let preservedExtras: Record<string, string> = {};
  try {
    preservedExtras = parseLarkEnvExtras(await readFile(envPath, "utf8"));
  } catch (error) {
    if (!(typeof error === "object" && error !== null && "code" in error && (error as NodeJS.ErrnoException).code === "ENOENT")) {
      throw error;
    }
  }
  const lines = [
    "# Generated by TaroCub lark wizard. Do not commit this file.",
    `LARK_APP_ID=${quoteEnvValue(values.appId)}`,
    `LARK_APP_SECRET=${quoteEnvValue(values.appSecret)}`,
    ...(values.domain ? [`LARK_DOMAIN=${quoteEnvValue(values.domain)}`] : []),
    `CCTB_LARK_STATE_DIR=${quoteEnvValue(stateDir)}`,
    `CCTB_LARK_INSTANCE=${quoteEnvValue(instanceName)}`,
    `TAROCUB_INSTANCE=${quoteEnvValue(instanceName)}`,
    `LARK_REQUIRE_MENTION_IN_GROUP=${quoteEnvValue(values.requireMentionInGroup === false ? "false" : "true")}`,
    ...Object.entries(preservedExtras).map(([key, value]) => `${key}=${quoteEnvValue(value)}`),
    "",
  ];
  await writeFile(envPath, lines.join("\n"), { encoding: "utf8", mode: 0o600 });
  return envPath;
}

function parseLarkEnvFile(content: string): Partial<LarkRuntimeEnv> {
  const result: Partial<LarkRuntimeEnv> = {};
  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) {
      continue;
    }
    const equalsIndex = line.indexOf("=");
    if (equalsIndex <= 0) {
      continue;
    }
    const key = line.slice(0, equalsIndex).trim();
    const value = parseEnvValue(line.slice(equalsIndex + 1).trim());
    if (isSupportedLarkEnvKey(key)) {
      result[key] = value;
    }
  }
  return result;
}

/**
 * Parse the non-whitelisted (extra) keys from a lark.env file — e.g. MCP API tokens
 * like IFIND_TOKEN that the operator added for the engine. Whitelisted Lark keys are
 * excluded (those are owned by loadLarkRuntimeEnv / written by writeLarkEnvFile).
 * Used both to pass extras through to the engine env and to preserve them across the
 * lark.env regeneration that happens on every service start.
 */
function parseLarkEnvExtras(content: string): Record<string, string> {
  const extras: Record<string, string> = {};
  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) {
      continue;
    }
    const equalsIndex = line.indexOf("=");
    if (equalsIndex <= 0) {
      continue;
    }
    const key = line.slice(0, equalsIndex).trim();
    if (isSupportedLarkEnvKey(key) || !/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) {
      continue;
    }
    extras[key] = parseEnvValue(line.slice(equalsIndex + 1).trim());
  }
  return extras;
}

function isSupportedLarkEnvKey(key: string): key is keyof Pick<
  LarkRuntimeEnv,
  "LARK_APP_ID" | "LARK_APP_SECRET" | "LARK_DOMAIN" | "CCTB_LARK_STATE_DIR" | "CCTB_LARK_INSTANCE" | "LARK_REQUIRE_MENTION_IN_GROUP" | "CCTB_LARK_DEBUG" | "TAROCUB_INSTANCE" | "CODEX_TELEGRAM_INSTANCE"
> {
  return key === "LARK_APP_ID" ||
    key === "LARK_APP_SECRET" ||
    key === "LARK_DOMAIN" ||
    key === "CCTB_LARK_STATE_DIR" ||
    key === "CCTB_LARK_INSTANCE" ||
    key === "LARK_REQUIRE_MENTION_IN_GROUP" ||
    key === "CCTB_LARK_DEBUG" ||
    key === "TAROCUB_INSTANCE" ||
    key === "CODEX_TELEGRAM_INSTANCE";
}

function parseEnvValue(value: string): string {
  if (value.length >= 2 && value.startsWith("\"") && value.endsWith("\"")) {
    return value.slice(1, -1).replace(/\\(["\\$`])/g, "$1").replace(/\\n/g, "\n");
  }
  if (value.length >= 2 && value.startsWith("'") && value.endsWith("'")) {
    return value.slice(1, -1).replace(/'\\''/g, "'");
  }
  return value;
}

function quoteEnvValue(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, "\\\"").replace(/\$/g, "\\$").replace(/`/g, "\\`").replace(/\n/g, "\\n")}"`;
}
